### PR TITLE
Change the RootSync helm.namespace field default value

### PR DESCRIPTION
**Pull request by xinnywinne**
Change the helm.namespace default value from "config-management-system"
to "default" to be consistent with other tools: Helm, Kustomize etc.

### CODE REVIEW

**Comment by haiyanmeng** [comment]
@xinnywinne , please rebase your PR.

**Comment by haiyanmeng** [comment]
It seems that this duplicates https://github.com/GoogleContainerTools/kpt-config-sync/pull/137.

**Comment by nan-yu** [comment]
This PR cherrypicks #137 to the v1.13 branch.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Comment by haiyanmeng** [comment]
> This PR cherrypicks #137 to the v1.13 branch.

Ahh. I see. I didn't notice that.

**Comment by xinnywinne** [comment]
> It seems that this duplicates #137.

Thanks Haiyan for your review, just see your comment :)

**Pull request merged**
