### PR TITLE
Change VPA e2e test to use dynamic generation validation

### PR DESCRIPTION
**Pull request by victorpras**
Changed generation validation to be more dynamic instead of hardcoding the expected number. While individual test runs always starts from 1, CI runs use shared environment and generation numbers may have been changed by other test runs

### CODE REVIEW

**Review by sdowell — CHANGES_REQUESTED** [review]
Please make the commit message more descriptive. I can infer what was broken by looking at the diff but the commit message should provide context as well

**Comment by sdowell** [comment]
fyi looks like the PR description was updated but not the commit message

**Comment by victorpras** [comment]
Added more description and commit message has been updated

**Review by sdowell — APPROVED** [review]
/lgtm

**Pull request merged**
