### PR TITLE
test: Only check declared_resources metric

### PR DESCRIPTION
**Pull request by tiffanny29631**
The fix https://github.com/GoogleContainerTools/kpt-config-sync/pull/1232 only affects declared_resources from Config Sync.

The metric from RG controller may take longer to be ready. Skip checking for those target values for now.

### CODE REVIEW

**Review by karlkfi — APPROVED** [review]
/lgtm

**Review by karlkfi — APPROVED** [review]
/lgtm

**Review by sdowell — APPROVED** [review]
/lgtm

**Pull request merged**
