### PR TITLE
Add a nomostest field-manager

### PR DESCRIPTION
**Pull request by karlkfi**
Use Apply instead of Create when ignoring IsAlreadyExists

### CODE REVIEW

**Review by nan-yu — APPROVED** [review]
/lgtm

**Comment by karlkfi** [comment]
The fact that this breaks tests now is scary.
It passed tests without the Create -> Apply changes, in another PR.
So that means one or more of those Apply calls is breaking many of the tests... I wonder if it's causing conflicts between managed RootSyncs and the config in nt.RootRepos...

**Comment by karlkfi** [comment]
Ah, I think I know what the problem is.

The `Apply` in `ValidateMultiRepoDeployments` is reverting RootSync changes made by individial tests after test setup.

I think we may need to remove that Apply/Create and replace it with one in test setup, but for now, I'll just undo the Clean->Apply there, since it worked before.

**Comment by karlkfi** [comment]
/retest

I think this is a flakey failure in TestDeclareImplicitNamespace. The Deployment didn't come up.

**Comment by karlkfi** [comment]
/retest 

```
I0202 22:16:58.049312   18143 root.go:196] New source errors for RootSync config-management-system/my-rs: [{Code:2002 ErrorMessage:KNV2002: API discovery failed: APIServer error: unable to retrieve the complete list of server APIs: rbac.authorization.k8s.io/v1: context deadline exceeded, v1: context deadline exceeded
```

I think the kind cluster died in the presubmit...

**Pull request merged**
