### PR TITLE
Use kubectl to deploy necessary RBAC in mono repo apiservice_test (#73)

### PR DESCRIPTION
**Pull request by nan-yu**
The mentioned RBAC includes necessary ClusterRole and ClusterRoleBindings for the backend deployment to work in GKE environment. In Config Sync CI after each test it will try to reset the test git repo to default. Removing this RBAC from git directly is blocked by importer as it detects the commit of removal will reduce the count of cluster resource from more than 1 down to 0.

Thus manually deploying RBAC when test is running in mono repo mode.

### CODE REVIEW

**Comment by karlkfi** [comment]
Note: This is a hack to fix a problem that's already been fixed on the main branch in a more robust way, with a 'safety' ClusterRole. Let's make sure this stays only on the v1.13 branch.

**Comment by nan-yu** [comment]
@tiffanny29631 Can you update the test on the main branch given that we have already had a `safety` ClusterRole? The ClusterRole prevents from deleting more than 1 existing cluster-scoped resources from the cluster in one shot.

**Comment by karlkfi** [comment]
@nan-yu I dont think main need updating. The new safety ClusterRole I added ALLOWS tests to delete all their cluster-scoped resources. I added it so that individual tests don't need to do this dance.

**Comment by nan-yu** [comment]
re: https://github.com/GoogleContainerTools/kpt-config-sync/pull/142#issuecomment-1261344293

>  Note: This is a hack to fix a problem that's already been fixed on the main branch in a more robust way, with a 'safety' ClusterRole. Let's make sure this stays only on the v1.13 branch.

The same change is already in the main branch before the ClusterRole fix was merged. Using `kubectl apply` bypasses the safety check issue. We can switch back to use Config Sync to manage the RBAC, but it is not worth it.

**Pull request merged**
