### PR TITLE
update base images to address vulnerabilities

### PR DESCRIPTION
**Pull request by sdowell**

### CODE REVIEW

**Review by mortent — APPROVED** [review]
/lgtm

**Review by janetkuo — APPROVED** [review]
/lgtm

**Review by nan-yu — APPROVED** [review]
/lgtm

**Review by nan-yu — APPROVED** [review]
/lgtm

**Review by nan-yu — APPROVED** [review]
/lgtm

**Review by nan-yu — COMMENTED** [review]
/lgtm

**Pull request merged**
