### PR TITLE
Use gcenode v1.0.1 in config sync to fix CVE

### PR DESCRIPTION
**Pull request by tiffanny29631**
b/285010427

### CODE REVIEW

**Comment by karlkfi** [comment]
Why did the release verioning scheme change from date to version?

**Comment by tiffanny29631** [comment]
Re @karlkfi This change follows an updated procedure [go/acm-gcenode](https://goto.google.com/acm-gcenode)

**Comment by karlkfi** [comment]
Why did the process change?
All the previous releases (except v1.0.0) used date for tag.
https://console.cloud.google.com/gcr/images/config-management-release/global/gcenode-askpass-sidecar?mods=logs_tg_prod&project=config-management-release

**Comment by karlkfi** [comment]
Looks like @sdowell changed it in cl/533300962 for b/282821665 as part of release automation with Louhi. But there was still apparently a dated release cut between 1.0.0 and 1.0.1.

**Comment by karlkfi** [comment]
Looks like it's well documented now, even if the change seems a little arbitrary. I do prefer the semver. I was just wondering when/why.

**Review by karlkfi — APPROVED** [review]
/lgtm

**Review by sdowell — APPROVED** [review]

**Pull request merged**
