### PR TITLE
separate acm-psp manifest from OSS config-sync-manifest

### PR DESCRIPTION
**Pull request by sdowell**
Fixes: https://github.com/GoogleContainerTools/kpt-config-sync/issues/167

### CODE REVIEW

**Comment by karlkfi** [comment]
Are there any readme instructions that need updating to reflect this change?

**Comment by sdowell** [comment]
> Are there any readme instructions that need updating to reflect this change?

@karlkfi 

I updated the instructions for installing from release manifests. The dev guide still points users to use the `build-oss` target for building from source, so I'm not touching that here. https://github.com/GoogleContainerTools/kpt-config-sync/pull/148 consolidates to the single target.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
