### PR TITLE
Bump Kustomize version to fix CVE

### PR DESCRIPTION
**Pull request by victorpras**

### CODE REVIEW

**Review by nan-yu — COMMENTED** [review]
https://github.com/GoogleContainerTools/kpt-config-sync/blob/main/pkg/hydrate/tool_util.go#L48 also needs to be updated.

**Comment by victorpras** [comment]
> https://github.com/GoogleContainerTools/kpt-config-sync/blob/main/pkg/hydrate/tool_util.go#L48 also needs to be updated.

I missed that, updated now.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
