### PR TITLE
chore: git sync update to v4.3.0-gke.3__linux_amd64

### PR DESCRIPTION
**Pull request by mikebz**
bumping up the git-sync even though it's not clear that it's addressing any CVEs

### CODE REVIEW

**Comment by tiffanny29631** [comment]
Is there any CVE reported before making this build?

**Comment by mikebz** [comment]
in general yes there aer CVE notifications.

**Review by sdowell — APPROVED** [review]
This change is acceptable but it doesn't address the CVE findings on the current `git-sync` image. The findings are related to OS packages and require for the image to be rebuilt

/lgtm

**Comment by mikebz** [comment]
yes, this was a low hanging fruit while I was looking into the git sync updates.

**Pull request merged**
