### PR TITLE
[chore] Bump otelcontribcol to 0.99.0-gke.1

### PR DESCRIPTION
**Pull request by tiffanny29631**
Change log https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.99.0

No breaking change applied to components used by Config Sync since 0.91.0.

Enhancements found for opencensusreceiver, filterprocessor, resourcedetectionprocessor.

### CODE REVIEW

**Comment by mikebz** [comment]
interesting that a go test has bombed out.  These should not be dependent on metrics.  I am going to re-test this and see if this is a flake.

**Comment by mikebz** [comment]
looks like it was an environmental issue.

**Comment by tiffanny29631** [comment]
The latest tests seem to be passing

**Review by karlkfi — APPROVED** [review]
/lgtm

**Pull request merged**
