### PR TITLE
chore: update debian-base:bookworm image

### PR DESCRIPTION
**Pull request by mikebz**

### CODE REVIEW

**Review by nan-yu — APPROVED** [review]
/lgtm

**Comment by tiffanny29631** [comment]
Is this for vulnerability fix?

**Comment by nan-yu** [comment]
> Is this for vulnerability fix?

I believe so. An `unspecified` CVE was fixed in the new image.

**Comment by tiffanny29631** [comment]
Ack, thanks

**Comment by mikebz** [comment]
I can tag it up with a CVE next time, but there could be multiple.

**Comment by tiffanny29631** [comment]
Or easier just linking it to the b/? Not a big problem though

**Pull request merged**
