### PR TITLE
Bump otel-agent's memory requests/limits on Autopilot clusters

### PR DESCRIPTION
**Pull request by nan-yu**

### CODE REVIEW

**Review by sdowell — APPROVED** [review]

**Comment by karlkfi** [comment]
Can you provide examples of oomkills with 32Mi?

The profiling I did used very low resources, but I didn't particularly stress the metrics load. So it's reasonable to assume it needs more. [go/config-sync-reconciler-profiling](http://goto.google.com/config-sync-reconciler-profiling)

**Comment by karlkfi** [comment]
/hold

I'm fine with the change, just needs justification documented.

**Comment by nan-yu** [comment]
> Can you provide examples of oomkills with 32Mi?
> 
> The profiling I did used very low resources, but I didn't particularly stress the metrics load. So it's reasonable to assume it needs more. [go/config-sync-reconciler-profiling](http://goto.google.com/config-sync-reconciler-profiling)

3 occurences of `container "otel-agent" terminated with exit code 137 and reason "OOMKilled"` in https://storage.googleapis.com/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-autopilot-rapid/1710031135938973696/build-log.txt.

OOMKilled occurred after the new open telemetry image was merged, so it is highly possible that the newer version consumes more memory.

**Comment by karlkfi** [comment]
The example failed 3 tests with OOMKilled:
- TestNamespaceStrategy
- TestConflictingDefinitions_RootToRoot
- TestReconcilerFinalizer_Orphan

Can you run those on autopilot manually with the memory increased and confirm they pass?

Also, try TestStressMemoryUsage.

**Comment by karlkfi** [comment]
I've made a Cloud Monitoring dashboard for watching resource usage while running tests: https://console.cloud.google.com/monitoring/dashboards/builder/df95d6cd-ceab-4ab7-a510-ef33c52a7176;duration=PT30M?f.rlabel.cluster_name=karlisenberg-auto-1&f.smlabel.top_level_controller_type=Deployment&f.smlabel.top_level_controller_name=root-reconciler

Feel free to copy it, change the cluster_name and/or project and watch the resource usage of the above tests as they run or after. That will help determine how much memory is actually being used to avoid over-allocating too much.

**Comment by karlkfi** [comment]
Related issue I'm working on: b/300294367 (I haven't written a stress test specifically for otel-agent yet tho)

**Comment by nan-yu** [comment]
> The example failed 3 tests with OOMKilled:
> 
> * TestNamespaceStrategy
> * TestConflictingDefinitions_RootToRoot
> * TestReconcilerFinalizer_Orphan
> 
> Can you run those on autopilot manually with the memory increased and confirm they pass?
> 
> Also, try TestStressMemoryUsage.

Not only that three tests. The OOMKilled seems to occur in any arbitrary test: 
image.

I tried to run one of them and it passed for me 3 times, but it's hard to confirm it will pass for other test. I would like to get it confirmed via CI.

**Comment by karlkfi** [comment]
CI can confirm that it's enough, but unfortunately CI can't show whether it's too much or not. That's why I've been running manual tests first to try to minimize the resources as much as possible.

In the future we may have a way to record resources used vs requested in CI, but it would require effectively replicating VPA, so it's not obvious that it would be a good use of time.

My main concern here is that I had to justify and get approval for these resources already. It's not clear to me if we need to justify and get approval for similar increases as well.

**Comment by nan-yu** [comment]
The current Autopilot memory requests/limits are all binary exponents.
I thought we use them to avoid auto-adjustment from Autopilot.
The minimal binary exponent larger than 32MB is 64MB. 

If that is not hard requirement, we can try with other numbers like 40MB or 50MB.

**Comment by nan-yu** [comment]
> Also, try TestStressMemoryUsage.

TestStressMemoryUsage stresses the memory usage for the reconciler, but not necessarily otel-agent.
I feel like I'm down to a rabbit hole that we need to stress each container.

**Comment by nan-yu** [comment]
> I've made a Cloud Monitoring dashboard for watching resource usage while running tests: https://console.cloud.google.com/monitoring/dashboards/builder/df95d6cd-ceab-4ab7-a510-ef33c52a7176;duration=PT30M?f.rlabel.cluster_name=karlisenberg-auto-1&f.smlabel.top_level_controller_type=Deployment&f.smlabel.top_level_controller_name=root-reconciler
> 
> Feel free to copy it, change the cluster_name and/or project and watch the resource usage of the above tests as they run or after. That will help determine how much memory is actually being used to avoid over-allocating too much.

I don't have access to your dashboard. Can you grant me the reader access?

**Comment by karlkfi** [comment]
The dashboard is in stolos-dev. You have owner.

But yeah, the profiling is tedious. I've been working on it for a few weeks now. I have two more stress tests locally for OCI and Helm, but neither significantly stresses otel-agent.

Like I said, I suspect 64Mi is fine and minimal enough. I just recently set it to 32Mi and got that approved so it seems like increasing it should also be profiled and justified and approved. But maybe @janetkuo feels otherwise.

**Comment by karlkfi** [comment]
If @janetkuo is ok with it, I'm ok with increasing to 64Mi and then maybe doing more profiling later, but I don't have any real numbers yet to really justify why we need 64Mi, and I'm not even sure if it's even worth profiling for that small of a change.

**Comment by nan-yu** [comment]
> If Janet Kuo is ok with it, I'm ok with increasing to 64Mi and then maybe doing more profiling later, but I don't have any real numbers yet to really justify why we need 64Mi, and I'm not even sure if it's even worth profiling for that small of a change.

Do the memory requests/limits for Autopilot have to be in a binary exponent?

**Comment by janetkuo** [comment]
I'm okay with increasing to 64Mi to deflake the CI, and do more profiling later

**Comment by karlkfi** [comment]
> Do the memory requests/limits for Autopilot have to be in a binary exponent?

Not individually by container, but the total memory for the pods ends up being a multiple of 256Mi because of the combination of CPU rounding up to the nearest 250m and Memory:CPU ratio needing to be at least 1GiB:1CPU. So I used binary squares to make the math simpler. But it's still rather tedious to calculate whether adjustment will occur.

Simulation: https://github.com/GoogleContainerTools/kpt-config-sync/blob/main/e2e/testcases/reconciler_manager_test.go#L889

**Comment by nan-yu** [comment]
> If Janet Kuo is ok with it, I'm ok with increasing to 64Mi and then maybe doing more profiling later, but I don't have any real numbers yet to really justify why we need 64Mi, and I'm not even sure if it's even worth profiling for that small of a change.

Just a quick update on the memory usage for the otel-agent container on Autopilot.
The data samples in Metrics Explorer didn't capture the peak usage: 
image.

I was running `kubectl top po -n config-management-system -l app=reconciler --containers | grep otel-agent` every minute. The average memory usage was around 30MiB and the peak usage was 41MiB.
```
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   4m           40Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   3m           27Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   3m           27Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           40Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           27Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           27Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   3m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           28Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   1m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   1m           29Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   3m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           28Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   10m          20Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   1m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   2m           27Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   3m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   2m           27Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   2m           28Mi            
root-reconciler-rr3-797bf4689d-nwmv2           otel-agent   9m           26Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   2m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   1m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   2m           28Mi            
root-reconciler-rr3-797bf4689d-nwmv2           otel-agent   2m           26Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   3m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   2m           28Mi            
root-reconciler-8458d6d77d-cmkf8               otel-agent   2m           28Mi            
root-reconciler-rr1-6bcd9f55d8-6m5fv           otel-agent   2m           29Mi            
root-reconciler-rr2-67757d8ccc-tm27g           otel-agent   2m           28Mi            
root-reconciler-rr3-797bf4689d-nwmv2           otel-agent   2m           27Mi            
ns-reconciler-ns-2-nr1-3-68cff5c7cc-7gtgx      otel-agent   1m           41Mi            
ns-reconciler-test-ns-nr1-3-74d9d58dc9-6lglx   otel-agent   1m           28Mi            
ns-reconciler-test-ns-nr2-3-5ccb696d5c-p4fg2   otel-agent   2m           27Mi   
```

With that, I think 64MiB as the default memory requests/limits for the otel-agent seems reasonable.

**Pull request merged**
