### PR TITLE
go mod tidy

### PR DESCRIPTION
**Pull request by sdowell**

### CODE REVIEW

**Comment by justinsb** [comment]
I saw this in the most recent test failure:

```
E0818 23:57:23.219244       1 logr.go:265]  "msg"="Failed to get API Group-Resources" "error"="Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"  
E0818 23:57:23.219285       1 logr.go:265] setup "msg"="starting manager" "error"="Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"  
```

In KCC we observed something similar when the test pod didn't have enough memory and it was OOMing (and presumably killing kube-apiserver).  We eventually noticed an OOM event on one of the pods there, but I haven't seen any direct evidence in the logs here ... yet.  But we just doubled the memory and (anecdotally) the tests did become much more consistent.

**Comment by janetkuo** [comment]
@justinsb thanks for sharing the observation! @sdowell it looks like something we can do to reduce test flakiness.

**Review by janetkuo — APPROVED** [review]
/lgtm

**Comment by sdowell** [comment]
@justinsb Thank you so much for sharing the observation! In your case was it an issue of the available memory on the node or with the pod resource requests/limits?

**Pull request merged**
