### PR TITLE
Update golangci-lint to v1.52.0

### PR DESCRIPTION
**Pull request by karlkfi**
- Ignore "should have a package comment" for now (many)
- Ignore "error strings should not be capitalized", because Config Sync uses errors for user-readable status messages.

### CODE REVIEW

**Comment by sdowell** [comment]
perhaps we could consider cherry picking https://github.com/GoogleContainerTools/kpt-config-sync/pull/465 instead? This would make it simpler to rebase the feature branch

**Comment by karlkfi** [comment]
@sdowell https://github.com/GoogleContainerTools/kpt-config-sync/pull/465 looks too big. linter changes should probably be separate from version bumps.

When you update to 1.19 tho, you will need to update the staticcheck linter to 1.1.9. I'm only updating it to 1.17 here.

**Comment by karlkfi** [comment]
/unhold

I fixed all the unused parameter failures.

**Comment by sdowell** [comment]
Agreed it would have been an easier cherry pick if I had separated the linter change. That being said, is there an urgent reason for this PR? #465 is already submitted, so we could get the linter bump when merging the feature branch

**Comment by karlkfi** [comment]
Linting is failing on https://github.com/GoogleContainerTools/kpt-config-sync/pull/412

Not super sure why, but I realized our lint-go.sh script was using master to download the install script, instead of the versioned tag. So I pinned it, but it was still failing. It also tends to hang occasionally. So I upgraded it, which caused test failures. So I fixed them

**Pull request merged**
