### PR TITLE
More cherry-pick CVE fixes for 1.18.1

### PR DESCRIPTION
**Pull request by karlkfi**
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1220
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1218
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1216
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1215
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1214
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1212
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1210
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1202
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/1195

### CODE REVIEW

**Comment by nan-yu** [comment]
#1220 is not for CVE fixes. Do we want to cherrypick that?

**Comment by karlkfi** [comment]
> https://github.com/GoogleContainerTools/kpt-config-sync/pull/1220 is not for CVE fixes. Do we want to cherrypick that?

I figured it would help more e2e tests pass more reliably on the release ci.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
