### PR TITLE
Print YAML instead of JSON on e2e validation error

### PR DESCRIPTION
**Pull request by karlkfi**
JSON takes less vertical space, but it significantly harder to read/scan quickly. Debug only runs on dev machines so this wont affect CI.

### CODE REVIEW

**Comment by karlkfi** [comment]
/retest

Looks like flakey cluster creation problem

**Review by nan-yu — APPROVED** [review]
/lgtm

**Comment by karlkfi** [comment]
/retest

`stream error: stream ID 2009; INTERNAL_ERROR; received from peer` go download flake

**Pull request merged**
