### PR TITLE
test: improve logging for flaky TestCRD test

### PR DESCRIPTION
**Pull request by sdowell**
This test has become increasingly flaky. Increasing the reconciler log level should help surface more of the reconciler logs when the test fails.

### CODE REVIEW

**Comment by karlkfi** [comment]
I think https://github.com/GoogleContainerTools/kpt-config-sync/pull/1342 will fix the flakiness in TestCRDDeleteBeforeRemoveCustomResourceV1, but I'm not 100% sure.

**Comment by karlkfi** [comment]
Nope, nevermind. THIS should fix it: https://github.com/GoogleContainerTools/kpt-config-sync/pull/1348

**Review by nan-yu — APPROVED** [review]
/lgtm

TestCRDDeleteBeforeRemoveCustomResourceV1 is still flaky. More logs would be useful for diagnosis.

**Pull request merged**
