### PR TITLE
Reduce askpass container default memory

### PR DESCRIPTION
**Pull request by victorpras**
After discussing with @janetkuo , we will reduce the askpass container default memory

### CODE REVIEW

**Comment by karlkfi** [comment]
This will reduce the limit in autopilot. Have you verified it won't OOM at the lower limit?

**Comment by victorpras** [comment]
> This will reduce the limit in autopilot. Have you verified it won't OOM at the lower limit?

I've run a few different setup for config sync and the memory consumption never seem to exceed 20M. Before the changes in https://github.com/GoogleContainerTools/kpt-config-sync/pull/814, the container was created with default memory value of 10M and afaict there was no issue with OOM

**Comment by janetkuo** [comment]
This is a follow-up of https://github.com/GoogleContainerTools/kpt-config-sync/pull/814

**Review by nan-yu — APPROVED** [review]
/lgtm

@haiyanmeng FYI, this also needs to be cherrypicked into v1.16.

**Pull request merged**
