### PR TITLE
chore: updated the golang.org/x/oauth2 to v0.24.0

### PR DESCRIPTION
**Pull request by mikebz**
http://b/378536256

### CODE REVIEW

**Review by nan-yu — COMMENTED** [review]
With the early expiration in the oauth library, do we still need another early expiration in askpass?

**Comment by karlkfi** [comment]
> With the early expiration in the oauth library, do we still need another early expiration in askpass?

Maybe. Maybe not.

For askpass, there's the added complexity that git-sync doesn't request a new token before every git command, and executes multiple in a row. 

But if I had to guess, we probably only need it in the oauth lib. 

Depending on how short the token expiration is set to, it might actually be problematic to reset it too early.

Does this update cover all the cases in b/378536256?

**Comment by mikebz** [comment]
this is just a library update.

**Comment by nan-yu** [comment]
> Does this update cover all the cases in b/378536256?

Nope. The oauth update only covers the ComputeTokenSource, but not `external-account` for fleet workload identity.

In that regards, it is good to keep it in the askpass.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
