### PR TITLE
[resource-group-controller] update image with vulnerability fix

### PR DESCRIPTION
**Pull request by tiffanny29631**

### CODE REVIEW

**Comment by karlkfi** [comment]
why is the PR tagged  `[CI]`?

**Comment by tiffanny29631** [comment]
re @karlkfi it's for CI test purpose

**Comment by sdowell** [comment]
Some added context - prior to https://github.com/GoogleContainerTools/kpt-config-sync/pull/687, which was very recently merged, the resource-group manifest was primarily used for CI. The resource-group manifest was being managed separately from the config sync manifests upstream. With 687 submitted, future releases will ship the resource-group manifest bundled with the config sync manifests.

**Comment by tiffanny29631** [comment]
Thanks for the reminder Sam. Modified PR title to fit the latest change

**Review by sdowell — APPROVED** [review]

**Pull request merged**
