### PR TITLE
test: add the parent directory to the package path

### PR DESCRIPTION
**Pull request by nan-yu**

### CODE REVIEW

**Comment by karlkfi** [comment]
why?

**Review by sdowell — APPROVED** [review]
/lgtm

**Comment by sdowell** [comment]
> why?

Looks like it was pointing to the wrong subdirectory under `e2e/testdata`

**Comment by nan-yu** [comment]
> > why?
> 
> Looks like it was pointing to the wrong subdirectory under `e2e/testdata`

**Comment by nan-yu** [comment]
> why?

The `ImageSourcePackage` used to assume the sourcePackage was under `../testdata/hydration`. https://github.com/GoogleContainerTools/kpt-config-sync/pull/1160/files#diff-1b3101a76e7a4bdea3393845932245be6356bea2cd9847d7b9ee9f05b04b82be removed `hydration` from the path. The update for this file is missing.

**Pull request merged**
