### PR TITLE
Postprocess the junit report by appending a testcases.Failure (#329)

### PR DESCRIPTION
**Pull request by tiffanny29631**
The testgrid failed to autocloase the bug because the testcases.Failure entry wasn't removed from a successful run.

This commit postprocesses the junit report to ensure the bug can be autoclosed immediately.

*** Cherry-pick into release branch to clear the false red in release CI

### CODE REVIEW

**Comment by tiffanny29631** [comment]
Need this 06b791b4de6e33246d77febc9adff48dfc6aa6fb

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
