### PR TITLE
cherry-pick: Changes for v1.19.1

### PR DESCRIPTION
**Pull request by sdowell**
The key cherry pick is https://github.com/GoogleContainerTools/kpt-config-sync/pull/1372, which adds the githubapp authentication type for 1.19.1.

The other cherry picks are mostly refactors and test improvements. Cherry picking these should help:
- address some test speed/stability issues
- minimize future cherry pick conflicts associated with refactoring

### CODE REVIEW

**Comment by nan-yu** [comment]
Do we need to cherrypick all?

The following seems can be deleted without any merge conflicts:
- [Add profiling tests and watch filtering doc](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1384)
- [test: Add e2e tests to cover additional scenarios where external files are rendered (https://github.com/GoogleContainerTools/kpt-config-sync/pull/1393)
- [Update OWNERS_ALIASES](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1394)
- [update clientgen to use helper script](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1399)
- [chore: bump golangci-lint to 1.60.3](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1405)

**Comment by sdowell** [comment]
> Do we need to cherrypick all?
> 
> The following seems can be deleted without any merge conflicts:
> 
> * [Add profiling tests and watch filtering doc](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1384)
> * [test: Add e2e tests to cover additional scenarios where external files are rendered](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1393)
> * [Update OWNERS_ALIASES](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1394)
> * [update clientgen to use helper script](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1399)
> * [chore: bump golangci-lint to 1.60.3](https://github.com/GoogleContainerTools/kpt-config-sync/pull/1405)

These changes are either low risk or create cherry pick conflicts if dropped. I opted to just fast forward to simplify current/future cherry pick conflicts.

> Add profiling tests and watch filtering doc

This introduces some conflicts, because some of the subsequent changes touch the e2e tests (e.g. `pauseDeploymentYAML`).

> test: Add e2e tests to cover additional scenarios where external files are rendered

This adds test coverage which should have been included in 1.19.0, so I think this cherry pick is warranted.

> Update OWNERS_ALIASES

Can be omitted, but is a low risk change.

> update clientgen to use helper script

Can be omitted.

> chore: bump golangci-lint to 1.60.3

Can be omitted, but is a low risk change.

**Review by nan-yu — APPROVED** [review]
/lgtm

**Pull request merged**
